"""
IntelliCredit v2 — Agent Execution Loop
========================================
The central orchestrator between the LLM and the environment.

Responsibilities:
  1. Parse LLM free-form output (via action_parser)
  2. Execute tool calls against live env (via tool_executor)
  3. Enforce 4-call limit + redundancy detection
  4. Submit final decisions and advance the environment step
  5. Compute tool-efficiency reward bonuses/penalties
  6. Emit structured per-step logs for GRPO training

Key functions:
  process_llm_step(llm_output, env, step_state) → StepResult
  build_system_prompt(obs)                       → str
  build_tool_result_message(tool_result)         → str
  create_step_state()                            → StepState dict
"""

import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

try:
    from .action_parser  import parse_llm_output
    from .tool_executor  import execute_tool, SUPPORTED_TOOLS
except ImportError:
    from server.action_parser  import parse_llm_output
    from server.tool_executor  import execute_tool, SUPPORTED_TOOLS

try:
    from ..models import IntelliCreditAction
except ImportError:
    from models import IntelliCreditAction


# ═══════════════════════════════════════════════════════════════
# CONSTANTS
# ═══════════════════════════════════════════════════════════════

MAX_TOOL_CALLS_PER_STEP  = 4      # 5th+ call → forced CONDITIONAL
REASONING_MIN_CHARS      = 50     # under this → quality penalty
PENALTY_EXTRA_CALL       = -0.10  # per call beyond limit
PENALTY_MALFORMED_CALL   = -0.05
PENALTY_REDUNDANT_CALL   = -0.10
PENALTY_SHORT_REASONING  = -0.20
PENALTY_OVER_LIMIT_FORCE = -0.50  # when decision forced by loop

BONUS_TOOL_HELPED_CORRECT  = 0.20  # called relevant tool + made correct decision
BONUS_COMPLIANCE_TOOL_RED  = 0.30  # called compliance on RED alert + rejected
BONUS_MARKET_TOOL_CONC     = 0.20  # called market intel near sector limit


# ═══════════════════════════════════════════════════════════════
# STEP STATE (tracks tool history within one env step)
# ═══════════════════════════════════════════════════════════════

def create_step_state() -> Dict[str, Any]:
    """
    Create a fresh per-step tracking dictionary.
    Pass this to process_llm_step; it is mutated in place across tool calls.
    Reset by caller at the start of each new environment step.
    """
    return {
        "tool_calls"        : [],       # list of {"tool": str, "args": dict, "result": dict}
        "tool_call_count"   : 0,        # increments for COST tools (not submit_decision)
        "redundant_calls"   : 0,
        "malformed_calls"   : 0,
        "forced_decision"   : False,    # True if loop exceeded 4-call limit
        "final_action"      : None,     # 0/1/2
        "final_reasoning"   : "",
        "parse_confidences" : [],
        "step_tool_penalty" : 0.0,
        "step_tool_bonus"   : 0.0,
        "step_completed"    : False,
        "env_obs"           : None,     # last IntelliCreditObservation
        "env_reward"        : 0.0,
        "log_entries"       : [],
    }


# ═══════════════════════════════════════════════════════════════
# STEP RESULT (returned to caller / training loop)
# ═══════════════════════════════════════════════════════════════

@dataclass
class StepResult:
    """Structured result returned from process_llm_step."""
    step_advanced    : bool           = False
    parse_type       : str            = "default_reject"
    tool_name        : Optional[str]  = None
    tool_result      : Optional[Dict] = None
    tool_display     : Optional[str]  = None
    action           : int            = 2
    reasoning        : str            = ""
    parse_confidence : float          = 0.0
    parse_failure    : bool           = False
    forced_decision  : bool           = False
    env_obs          : Any            = None
    env_reward       : float          = 0.0
    tool_efficiency_delta : float     = 0.0
    log              : Dict[str, Any] = field(default_factory=dict)


# ═══════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ═══════════════════════════════════════════════════════════════

def process_llm_step(
    llm_output : str,
    env        : Any,
    step_state : Dict[str, Any],
) -> StepResult:
    """
    Process one LLM output turn within a single environment step.

    Call repeatedly until StepResult.step_advanced is True.
    The caller should reset step_state via create_step_state() at
    the start of each new env step.

    Args:
        llm_output  : Raw text generated by the LLM.
        env         : Live IntelliCreditEnvironment instance.
        step_state  : Per-step mutable tracking dict (from create_step_state).

    Returns:
        StepResult — if step_advanced=False, inject tool_display into LLM context
                     and call again with next LLM output.
    """
    t0 = time.perf_counter()

    # ── Guard: already over tool limit → force decision ──────────
    if step_state["tool_call_count"] >= MAX_TOOL_CALLS_PER_STEP and not step_state["step_completed"]:
        return _force_decision(env, step_state, reason="MAX_TOOL_CALLS_EXCEEDED")

    # ── Parse ─────────────────────────────────────────────────────
    parsed = parse_llm_output(llm_output)
    step_state["parse_confidences"].append(parsed["parse_confidence"])

    _log(step_state, f"parse={parsed['parse_type']} confidence={parsed['parse_confidence']:.2f}")

    # ── Branch: tool call ─────────────────────────────────────────
    if parsed["parse_type"] == "tool_call":
        return _handle_tool_call(parsed, env, step_state, elapsed=time.perf_counter() - t0)

    # ── Branch: final decision ────────────────────────────────────
    return _handle_final_decision(parsed, env, step_state, elapsed=time.perf_counter() - t0)


# ═══════════════════════════════════════════════════════════════
# TOOL CALL HANDLER
# ═══════════════════════════════════════════════════════════════

def _handle_tool_call(
    parsed     : Dict,
    env        : Any,
    step_state : Dict,
    elapsed    : float,
) -> StepResult:
    tool_name = parsed["tool_name"]
    tool_args = parsed["tool_args"] or {}

    # ── Redundancy check ─────────────────────────────────────────
    is_redundant = _is_redundant(tool_name, tool_args, step_state["tool_calls"])
    if is_redundant:
        step_state["redundant_calls"] += 1
        step_state["step_tool_penalty"] += PENALTY_REDUNDANT_CALL
        _log(step_state, f"REDUNDANT tool call: {tool_name} — penalty {PENALTY_REDUNDANT_CALL}")
        # Still execute but mark penalty; counts toward limit
    
    # ── Execute via tool_executor ─────────────────────────────────
    tool_result = execute_tool(tool_name, tool_args, env)
    step_state["tool_call_count"] += 1
    step_state["tool_calls"].append({
        "tool"     : tool_name,
        "args"     : tool_args,
        "success"  : tool_result["success"],
        "redundant": is_redundant,
    })

    # Malformed penalty
    if not tool_result["success"]:
        step_state["malformed_calls"] += 1
        step_state["step_tool_penalty"] += PENALTY_MALFORMED_CALL
        _log(step_state, f"MALFORMED/ERROR tool {tool_name}: {tool_result['error']}")

    # Over-limit penalty for THIS call
    if step_state["tool_call_count"] > MAX_TOOL_CALLS_PER_STEP:
        step_state["step_tool_penalty"] += PENALTY_EXTRA_CALL
        _log(step_state, f"OVER_LIMIT call #{step_state['tool_call_count']}: {PENALTY_EXTRA_CALL}")

    # Update env's total tool call counter (world_model_confidence)
    env._total_tool_calls = getattr(env, "_total_tool_calls", 0) + 1
    env._step_tool_call_count = step_state["tool_call_count"]

    _log(step_state, f"Tool {tool_name} executed | call_count={step_state['tool_call_count']}")

    return StepResult(
        step_advanced    = False,
        parse_type       = "tool_call",
        tool_name        = tool_name,
        tool_result      = tool_result,
        tool_display     = tool_result["display_text"],
        action           = 2,
        reasoning        = parsed["reasoning"],
        parse_confidence = parsed["parse_confidence"],
        parse_failure    = parsed["parse_failure"],
        forced_decision  = False,
        log              = _snapshot_log(step_state, elapsed),
    )


# ═══════════════════════════════════════════════════════════════
# FINAL DECISION HANDLER
# ═══════════════════════════════════════════════════════════════

def _handle_final_decision(
    parsed     : Dict,
    env        : Any,
    step_state : Dict,
    elapsed    : float,
) -> StepResult:
    action    = parsed["action"]
    reasoning = parsed["reasoning"]

    # ── Reasoning quality check ───────────────────────────────────
    reasoning_penalty = 0.0
    if not reasoning or reasoning.startswith("[WARNING"):
        reasoning_penalty = PENALTY_SHORT_REASONING
        step_state["step_tool_penalty"] += reasoning_penalty
        _log(step_state, f"SHORT/EMPTY reasoning penalty: {reasoning_penalty}")
    elif len(reasoning) < REASONING_MIN_CHARS:
        reasoning_penalty = PENALTY_SHORT_REASONING
        step_state["step_tool_penalty"] += reasoning_penalty
        _log(step_state, f"REASONING < {REASONING_MIN_CHARS} chars: {reasoning_penalty}")

    # ── Compute tool efficiency bonus ─────────────────────────────
    tool_bonus = _compute_tool_bonus(action, step_state, env)
    step_state["step_tool_bonus"] = tool_bonus

    # ── Submit to env ─────────────────────────────────────────────
    action_obj = IntelliCreditAction(decision=action, reasoning=reasoning)
    episode_id_str = getattr(getattr(env, "_state", None), "episode_id", None)
    obs = env.step(action=action_obj, episode_id=episode_id_str)

    # ── Record ────────────────────────────────────────────────────
    step_state["final_action"]    = action
    step_state["final_reasoning"] = reasoning
    step_state["step_completed"]  = True
    step_state["env_obs"]         = obs
    step_state["env_reward"]      = obs.reward

    efficiency_delta = step_state["step_tool_bonus"] + step_state["step_tool_penalty"]
    _log(step_state, (
        f"DECISION submitted: action={action} | env_reward={obs.reward:.3f} "
        f"| tool_bonus={tool_bonus:.2f} | tool_penalty={step_state['step_tool_penalty']:.2f}"
    ))

    return StepResult(
        step_advanced        = True,
        parse_type           = parsed["parse_type"],
        tool_name            = None,
        tool_result          = None,
        tool_display         = None,
        action               = action,
        reasoning            = reasoning,
        parse_confidence     = parsed["parse_confidence"],
        parse_failure        = parsed["parse_failure"],
        forced_decision      = step_state["forced_decision"],
        env_obs              = obs,
        env_reward           = obs.reward,
        tool_efficiency_delta= efficiency_delta,
        log                  = _snapshot_log(step_state, elapsed),
    )


# ═══════════════════════════════════════════════════════════════
# FORCED DECISION (when tool limit exceeded)
# ═══════════════════════════════════════════════════════════════

def _force_decision(env: Any, step_state: Dict, reason: str) -> StepResult:
    """
    Force a CONDITIONAL decision when the 4-call limit is exceeded.
    Applies heavy penalty.
    """
    step_state["forced_decision"] = True
    step_state["step_tool_penalty"] += PENALTY_OVER_LIMIT_FORCE
    _log(step_state, f"FORCED DECISION ({reason}): CONDITIONAL | penalty={PENALTY_OVER_LIMIT_FORCE}")

    action_obj = IntelliCreditAction(
        decision=1,
        reasoning=f"[FORCED CONDITIONAL: {reason} — exceeded {MAX_TOOL_CALLS_PER_STEP} tool call limit]",
    )
    episode_id_str = getattr(getattr(env, "_state", None), "episode_id", None)
    obs = env.step(action=action_obj, episode_id=episode_id_str)

    step_state["final_action"]   = 1
    step_state["step_completed"] = True
    step_state["env_obs"]        = obs
    step_state["env_reward"]     = obs.reward

    efficiency_delta = step_state["step_tool_bonus"] + step_state["step_tool_penalty"]

    return StepResult(
        step_advanced        = True,
        parse_type           = "default_reject",
        action               = 1,
        reasoning            = f"Forced CONDITIONAL — {reason}",
        forced_decision      = True,
        env_obs              = obs,
        env_reward           = obs.reward,
        tool_efficiency_delta= efficiency_delta,
        log                  = _snapshot_log(step_state, 0.0),
    )


# ═══════════════════════════════════════════════════════════════
# TOOL EFFICIENCY BONUS COMPUTATION
# ═══════════════════════════════════════════════════════════════

def _compute_tool_bonus(action: int, step_state: Dict, env: Any) -> float:
    """
    Award bonuses when tool calls demonstrably helped the right decision.
    """
    bonus = 0.0
    tools_used = {c["tool"] for c in step_state["tool_calls"]}
    n_tools    = step_state["tool_call_count"]

    # No info gathered + wrong or default decision
    if n_tools == 0:
        return 0.0  # handled differently in scenario B (slight reduction applied in reward.py)

    # Bonus A: compliance check + RED alert present + rejected
    step = env._current_step - 1
    if step >= 0 and step < len(env._applications):
        meta = env._applications[step]["metadata"]
        alerts    = meta.get("alerts", [])
        red_alerts = [a for a in alerts if a.get("severity") == "RED"]
        if red_alerts and "check_compliance_status" in tools_used and action == 2:
            bonus += BONUS_COMPLIANCE_TOOL_RED

        # Bonus B: market intel called near sector concentration limit
        if "get_market_intelligence" in tools_used and env._portfolio:
            total = sum(env._portfolio.sector_exposure.values())
            max_pct = max(
                (v / max(total, 1) for v in env._portfolio.sector_exposure.values()),
                default=0.0,
            )
            if max_pct > 0.25:
                bonus += BONUS_MARKET_TOOL_CONC

        # Bonus C: financial report used on borderline case
        if "get_financial_report" in tools_used:
            hidden_pd = meta.get("hidden_pd", 0.5)
            if 0.15 <= hidden_pd <= 0.45:   # borderline range
                bonus += BONUS_TOOL_HELPED_CORRECT

    # Slight over-analysis penalty for 4 tools
    if n_tools == 4:
        bonus -= 0.10

    return round(bonus, 4)


# ═══════════════════════════════════════════════════════════════
# SYSTEM PROMPT GENERATOR
# ═══════════════════════════════════════════════════════════════

def build_system_prompt(obs: Any, memory_bank: Any = None) -> str:
    """
    Generate the full system prompt for the LLM Credit Officer at each step.

    Prompt layers (Phase 5):
      Layer 1: Base system role
      Layer 2: Current state (portfolio, macro, audit risk)
      Layer 3: Past lessons (from memory_bank — top 5 by severity)
      Layer 4: Current application data
      Layer 5: Tool documentation
      Layer 6: Decision format + hard rules
      Layer 7: Action request
    """
    app_summary = getattr(obs, "application_summary", None)
    summary_text = app_summary.text_summary if app_summary else "No application summary available."
    step       = obs.timestep
    total      = 50
    reg_warn   = obs.regulator_warning_level
    is_repeat  = obs.is_repeat_applicant
    attempt    = obs.attempt_number
    mem        = obs.memory_features if obs.memory_features else [0.0] * 10

    # Regulatory warning banner
    reg_banner = ""
    if reg_warn == 1:
        reg_banner = "\n⚠️  REGULATORY WARNING: 1 consecutive audit failure on record."
    elif reg_warn == 2:
        reg_banner = "\n🚨 REGULATORY ALERT: 2 consecutive failures — capital penalty applied!"
    elif reg_warn >= 3:
        reg_banner = "\n🔴 CRITICAL: 3 consecutive audit failures — next failure = SHUTDOWN!"

    # Repeat applicant banner
    repeat_banner = ""
    if is_repeat:
        repeat_banner = (
            f"\n⚠️  REPEAT APPLICANT — This borrower was REJECTED {attempt - 1} time(s) before. "
            "Surface metrics may have improved but underlying risk likely unchanged or HIGHER."
        )

    # Memory context
    npa_trend   = "↑ Worsening" if mem[3] > 0.05 else ("↓ Improving" if mem[3] < -0.05 else "Stable")
    audit_risk  = "HIGH ⚠️" if mem[5] > 0.7 else ("MODERATE" if mem[5] > 0.3 else "Low")

    # ── Phase 5: Lesson injection from memory bank ────────────────
    lessons_block = ""
    if memory_bank is not None:
        # memory_bank can be a MemoryBank instance or have get_lessons_text()
        if hasattr(memory_bank, "get_lessons_text"):
            lessons_text = memory_bank.get_lessons_text(n=5)
            if lessons_text:
                lessons_block = "\n" + lessons_text + "\n"

    prompt = f"""You are a Senior Credit Officer at IntelliCredit Bank.
You review MSME loan applications and must make credit decisions that balance yield, risk, and regulatory compliance.

═══ CURRENT STATE ═══
Episode Step  : {step} / {total}
NPA Rate      : {mem[0]:.1%} (rolling 10-step)
Approval Rate : {mem[1]:.0%} (last 10 decisions)
Audit Risk    : {audit_risk} (next audit in {max(0, int((1 - mem[5]) * 10))} steps approx.)
Macro Trend   : {npa_trend}{reg_banner}{repeat_banner}
{lessons_block}
═══ CURRENT APPLICATION ═══
{summary_text}

═══ AVAILABLE TOOLS ═══
You may call up to {MAX_TOOL_CALLS_PER_STEP} tools before submitting your decision.
Each tool call returns information. The step does NOT advance until you call submit_decision().

TOOL 1 — get_financial_report("company_name")
  Use when: Financial ratios look borderline; need historical trend data.
  Returns : 3-year revenue, EBITDA margins, debt schedule, auditor remarks.

  Example: get_financial_report("Bharat Industries Pvt. Ltd.")

TOOL 2 — check_compliance_status("company_name")
  Use when: Forensic RED alert present; governance score is low; DIN concerns.
  Returns : MCA filings, GST returns, DIN status, NCLT cases, CIBIL score, prior defaults.

  Example: check_compliance_status("Bharat Industries Pvt. Ltd.")

TOOL 3 — get_market_intelligence("sector_name")
  Use when: Sector risk unclear; portfolio concentration near limit; macro shock active.
  Returns : Sector stress, RBI advisory, peer NPA rate, headwinds/tailwinds, portfolio exposure.

  Example: get_market_intelligence("Manufacturing")

═══ SUBMITTING YOUR DECISION ═══
After gathering information, finalize with:

  submit_decision("APPROVE", "Your detailed reasoning here (minimum 50 characters)")
  submit_decision("CONDITIONAL", "Approve with conditions: require quarterly cash-flow statements...")
  submit_decision("REJECT", "Rejecting due to HR-01 DSCR below 1.0 and RED ITC_MISMATCH alert...")

DECISION MEANINGS:
  APPROVE      (0) → Full approval. Maximum yield, full default risk.
  CONDITIONAL  (1) → Conditional approval with covenant monitoring. Reduced exposure.
  REJECT       (2) → Mandatory if any Hard Rule triggered (HR-01 to HR-06).

HARD RULES (ANY of these = MANDATORY REJECT):
  HR-01: DSCR < 1.0           HR-04: Cheque bounce rate > 25%
  HR-02: Director disqualified HR-05: GST compliance < 40%
  HR-03: RED forensic alert   HR-06: Severe adverse media (>0.80)

ANTI-GAMING RULES:
  • Calling the same tool twice with the same arguments = penalty.
  • Calling more than {MAX_TOOL_CALLS_PER_STEP} tools = forced CONDITIONAL + penalty.
  • Submitting without reasoning = decision rejected.
  • Reasoning under 50 characters = quality penalty.

Begin your analysis now. Think step by step. Use tools when uncertain.
"""
    return prompt.strip()


# ═══════════════════════════════════════════════════════════════
# TOOL RESULT MESSAGE (inject into LLM context)
# ═══════════════════════════════════════════════════════════════

def build_tool_result_message(tool_result: Dict, tool_call_count: int) -> str:
    """Format the tool result to be injected back as the next user message."""
    status = "✅ Tool Result" if tool_result.get("success") else "❌ Tool Error"
    header = (
        f"\n[{status}: {tool_result.get('tool_name', '?')}] "
        f"(Call {tool_call_count}/{MAX_TOOL_CALLS_PER_STEP})\n"
    )
    return header + tool_result.get("display_text", "") + "\n\nContinue your analysis or submit your decision."


# ═══════════════════════════════════════════════════════════════
# UTILITIES
# ═══════════════════════════════════════════════════════════════

def _is_redundant(tool_name: str, args: Dict, prior_calls: List[Dict]) -> bool:
    """Check if this exact tool+args combo already appeared in current step."""
    for prev in prior_calls:
        if prev["tool"] == tool_name and prev["args"] == args:
            return True
    return False


def _log(step_state: Dict, message: str) -> None:
    step_state["log_entries"].append(message)


def _snapshot_log(step_state: Dict, elapsed: float) -> Dict[str, Any]:
    return {
        "tool_calls"         : list(step_state["tool_calls"]),
        "tool_call_count"    : step_state["tool_call_count"],
        "redundant_calls"    : step_state["redundant_calls"],
        "malformed_calls"    : step_state["malformed_calls"],
        "step_tool_penalty"  : step_state["step_tool_penalty"],
        "step_tool_bonus"    : step_state["step_tool_bonus"],
        "forced_decision"    : step_state["forced_decision"],
        "parse_confidences"  : list(step_state["parse_confidences"]),
        "elapsed_s"          : round(elapsed, 4),
        "entries"            : list(step_state["log_entries"]),
    }


# ═══════════════════════════════════════════════════════════════
# SELF-TEST
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import sys, os
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    from server.intellicredit_env import IntelliCreditEnvironment

    env = IntelliCreditEnvironment(task_id="task2")
    obs = env.reset(seed=7)

    print("=" * 70)
    print("  agent_loop.py Self-Test — 5 LLM output scenarios")
    print("=" * 70)

    # Print system prompt
    prompt = build_system_prompt(obs)
    print("\n[SYSTEM PROMPT] (truncated)")
    print(prompt[:600], "...")
    print()

    test_scenarios = [
        # (label, list_of_llm_turns)
        (
            "Scenario A: Tool call → submit_decision (happy path)",
            [
                "Let me check compliance first. check_compliance_status('Zenith Solutions Pvt. Ltd.')",
                "RED alert confirmed. submit_decision('REJECT', 'HR-03 triggered: RED ITC_MISMATCH forensic alert detected. Mandatory reject per policy.')",
            ]
        ),
        (
            "Scenario B: Direct decision (no tools)",
            ["This profile is clean with DSCR 1.85x. submit_decision('APPROVE', 'Strong financials, no alerts, Tier A borrower with clean compliance record.')"],
        ),
        (
            "Scenario C: 2 tools then decide (rich analysis)",
            [
                "get_financial_report('Bharat Manufacturing Ltd.')",
                "get_market_intelligence('Manufacturing')",
                "submit_decision('CONDITIONAL', 'Revenue declining 3 years, sector stress moderate. Approve with quarterly review covenants and collateral top-up requirement.')",
            ]
        ),
        (
            "Scenario D: Forced decision after 5 tool calls",
            [
                "get_financial_report('ABC Ltd')",
                "check_compliance_status('ABC Ltd')",
                "get_market_intelligence('Retail_Trading')",
                "get_financial_report('ABC Ltd')",  # redundant
                "check_compliance_status('ABC Ltd')",  # 5th call — triggers force
            ]
        ),
        (
            "Scenario E: Fallback keyword parse",
            ["After careful review, the risk is too high — REJECT."],
        ),
    ]

    for label, turns in test_scenarios:
        print(f"\n{'─'*65}")
        print(f"  {label}")
        print(f"{'─'*65}")
        state = create_step_state()
        for i, turn in enumerate(turns):
            print(f"  [LLM Turn {i+1}]: {turn[:80]!r}")
            result = process_llm_step(turn, env, state)
            if result.step_advanced:
                print(f"  → STEP ADVANCED | action={result.action} | reward={result.env_reward:.3f}")
                print(f"    tool_bonus={result.tool_efficiency_delta:.3f} | forced={result.forced_decision}")
                print(f"    parse_type={result.parse_type} | confidence={result.parse_confidence:.2f}")
                break
            else:
                print(f"  → TOOL CALL: {result.tool_name} | calls_so_far={state['tool_call_count']}")
                if result.tool_display:
                    print("  → " + result.tool_display.split("\n")[0])
        # Reset for next episode step
        if not state["step_completed"]:
            # Force close the step for test continuity
            env.step(IntelliCreditAction(decision=2), episode_id=None)

    print(f"\n{'='*70}")
    print("  All scenarios complete.")
    print(f"{'='*70}")
